name: Create a new bundle
on:
  push:
    branches: [main]
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install the dependencies
        run: npm install
      - name: Lint and format the code
        run: npm run lint && npm run format
      - name: Build the project
        run: npm run build
      - name: Create a new bundle directory
        run: mkdir -p bundle
      - name: Copy all the files and folders to the bundle directory
        run: mv docker-compose.yml www/ bundle/
      - name: Upload the compressed archive to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: gallery
          path: bundle
          if-no-files-found: error
